<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodingBase.DataAccess.URtde" Version="1.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HelixToolkit.SharpDX.Assimp" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converters\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ur\meshes\ur10e\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10e\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur10\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur16e\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur16e\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur16e\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur16e\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3e\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur3\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5e\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\base.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\forearm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\shoulder.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\upperarm.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\wrist1.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\wrist2.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\collision\wrist3.stl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\base.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\forearm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\shoulder.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\upperarm.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\wrist1.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\wrist2.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\meshes\ur5\visual\wrist3.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur10.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur10e.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur16e.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur3.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur3e.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur5.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ur\urdf\ur5e.urdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
